version: '3.8'
services:
  traefik:
    image: traefik:v2.10
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.filename=/etc/traefik/dynamic_conf.yml"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
      - traefik_letsencrypt:/letsencrypt
    networks:
      - webnet

  web:
    build: .
    labels:
      - "traefik.http.routers.my-cool-project.rule=Host()"
      - "traefik.http.routers.my-cool-project.entrypoints=websecure"
      - "traefik.http.routers.my-cool-project.tls.certresolver=le"
    depends_on:
      - traefik
    networks:
      - webnet

volumes:
  traefik_letsencrypt: {}

networks:
  webnet:
    external: false
